[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config', 'libffi', 'openssl']

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "streamlit run src/app.py --server.port $PORT --server.address 0.0.0.0" 